version: '3.8'

services:
  web:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["gunicorn", "src.server:application", "--bind", "0.0.0.0:8080", "--workers", "4"]
