# docker-compose.yml
version: '3.9'

services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    restart: unless-stopped
