[[menus]]
menu = "Home"
parent = ""
text = "Welcome to Kendal the home of Olrig Bank"

[[menus]]
menu = "Whats On"
parent = "Home"
text = "Links to sites that will keep you abreast about what is happening"

[[menus]]
menu = "Local"
parent = "Home"
text = "Olrig Bank's recommended local delights"

[[menus]]
menu = "Eating Out"
parent = "Local"
text = "Places we where we love to eat"

[[menus]]
menu = "Local Walks"
parent = "Local"
text = "Good walks to take close to the house"

[[menus]]
menu = "Activities"
parent = "Local"
text = "A wide variety of local activities"

[[menus]]
menu = "Shopping"
text = "Local Shops with character"
parent = "Local"

[[menus]]
menu = "Music"
text = "Live Music Venues"
parent = "Local"

[[menus]]
menu = "Festivals"
text = "Gatherings that are still come this year"
parent = "Home"

[[offerings]]
image = "whatsonkendal"
link = "https://visit-kendal.co.uk/"
menu = "Whats On"
text = "The Visit Kendal site to easiest way to find out what is going on in the town during your stay"

[[offerings]]
image = "Babaganoush"
link = "https://babaganoushkendal.co.uk/"
menu = "Eating Out"
text = "Baba Ganoush - What a place! When it is open"

[[offerings]]
image = "kendalcastle"
link = "https://www.alltrails.com/trail/england/cumbria/kendal-castle-trail"
menu = "Local Walks"
text = "Play the grand old Duke of Kendal!"

[[offerings]]
image = "qtm"
link = "https://www.quaker-tapestry.co.uk/"
menu = "Activities"
text = "The Quaker Tapestry tells the story of Quakers in 77 embroidered panels"

[[offerings]]
image = "kcw"
link = "https://lakelandclimbingcentres.co.uk/centre/kendalwall/"
menu = "Activities"
text = "Kids climbing the walls? Why not visit the Kendal Climbing Wall!"

[[offerings]]
menu = "Shopping"
text = "Watson & Wollard is a high quality traditional local butcher"
link = "https://www.facebook.com/watsonandwoollardbutchers/"
image = "watson-wollard"

[[offerings]]
menu = "Music"
text = "From folk to jazz"
link = "https://www.facebook.com/TheRiflemansArms/"
image = "riflemansarms"

[[offerings]]
menu = "Festivals"
text = "The Kendal Mountain Festival - The Everest of Festivals "
link = "https://www.kendalmountainfestival.com/"
image = "mountain"

